### ISSUE TITLE
Bug: Report when the menuitem is not visible , e.g. macos decides to not show it

### ISSUE THREAD

**Issue by jgoldhammer** [jgoldhammer/MeetingBar#5]
**App version**
current version
**Describe the bug**
When the macos systembar is full, the application is not shown. The user is confused and thinks that the application is not working.

**To Reproduce**

**Expected behavior**
the user should be informed when the status item disappears 

**Screenshots**

**Desktop (please complete the following information):**
 - macOS version: [e.g. 10.15.4]

**Additional context**
https://github.com/feedback-assistant/reports/issues/37

**Comment by leits** [comment]
What do you think about transferring it to the main repo?)

**Comment by jgoldhammer** [comment]
I cannot transfer it - the main repo is not visibile in the action "Transfer issue" - I will close it here and reopen a new issue
